pragma Singleton
import QtQuick 2.15

QtObject {
    readonly property string home: "nav.home"
    readonly property string map: "nav.map"
    readonly property string create: "nav.create"
    readonly property string documents: "nav.documents"
    readonly property string settings: "nav.settings"
    readonly property string back: "system.back"
    readonly property string forward: "system.forward"
    readonly property string close: "action.close"
    readonly property string more: "action.more"
    readonly property string search: "action.search"
    readonly property string save: "action.save"
    readonly property string add: "action.add"
    readonly property string edit: "action.edit"
    readonly property string remove: "action.delete"
    readonly property string exportFile: "action.export"
    readonly property string success: "status.success"
    readonly property string warning: "status.warning"
    readonly property string error: "status.error"
    readonly property string loading: "status.loading"
    readonly property string folder: "files.folder"
    readonly property string file: "files.file"
    readonly property string excel: "files.excel"
    readonly property string pdf: "files.pdf"
    readonly property string location: "map.location"
    readonly property string marker: "map.marker"
    readonly property string calicata: "geotechnical.calicata"
    readonly property string talud: "geotechnical.talud"
    readonly property string stratigraphy: "geotechnical.stratigraphy"
    readonly property string geomechanics: "geotechnical.geomechanics"
}
