const fs = require('fs');
const assert = require('assert');
const vm = require('vm');
const service = fs.readFileSync('src/cpp/renditionexportservice.h', 'utf8');
const exporter = fs.readFileSync('androidcalicataexporter.cpp', 'utf8');
const qml = fs.readFileSync('qml/Mobile/pages/CalicatasEditorPage.qml', 'utf8');
assert(service.includes('rpc/ensure_my_calicata_exports_folder_v01'), 'Queue must resolve exports beside the server-bound JSON');
assert(service.includes('{"p_parent_node_id",row.value("parentNodeId")}'), 'Binary reservation must use the resolved folder');
assert(service.includes('intent.value("calicataId")'), 'Process recovery must preserve calicata identity');
assert(service.includes('row["remoteFolderPath"]=folder.value("display_path")'), 'Expose the real folder path');
assert(exporter.includes('"Calicatas/exports/"'), 'New Excel operations must have a distinct destination from legacy root exports');
assert(exporter.includes('header.value("remoteCalicataId", header.value("remote_calicata_id"))'), 'Use the remote calicata identity, not the local instance UUID');
const start = qml.indexOf('function _excelDrivePath(');
assert(start >= 0, 'UI must show the actual folder, without inventing a hierarchy');
const end = qml.indexOf('function _finishExcelExport(', start);
const context = vm.createContext({});
vm.runInContext(qml.slice(start, end), context);
assert.strictEqual(context._excelDrivePath({remoteFolderPath:'06_GABINETE/exports'},'Proyecto A','CA.xlsx'), 'Proyecto A › 06_GABINETE › exports › CA.xlsx');
assert.strictEqual(context._excelDrivePath({remoteFolderPath:'06_GABINETE/Ensayos/exports'},'Proyecto A','CA.xlsx'), 'Proyecto A › 06_GABINETE › Ensayos › exports › CA.xlsx');
assert.strictEqual(context._excelDrivePath({},'Proyecto A','CA.xlsx'), 'Proyecto A › carpeta del JSON › exports › CA.xlsx');
console.log('PASS exports: destination source guards, recovery identity, actual UI path');
