"""Read-only check of an XLSX generated by the real application exporter."""
import argparse
import openpyxl
from zipfile import ZipFile
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser()
parser.add_argument('xlsx')
args = parser.parse_args()
book = openpyxl.load_workbook(args.xlsx)
assert book.sheetnames == ['Calicata'], 'Expected one Calicata worksheet'
sheet = book['Calicata']
with ZipFile(args.xlsx) as package:
    root = ET.fromstring(package.read('xl/workbook.xml'))
    ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
    names = root.findall('s:definedNames/s:definedName', ns)
    scopes = [(name.get('name'), name.get('localSheetId')) for name in names]
    assert len(scopes) == len(set(scopes)), 'Duplicate scoped defined names / print areas'
for image in sheet._images:
    first = image.anchor._from.col
    last = getattr(image.anchor, 'to', image.anchor._from).col
    assert not (first < 46 and last > 9 and image.anchor._from.row >= 21), \
        'A body image covers editable description/sample/laboratory cells'
assert sheet['BE1'].value is None, 'Data must live inside the actual form'
assert any(sheet.cell(row, 31).value for row in range(22, sheet.max_row + 1)), \
    'No native sample interval exists in column AE'
assert any(sheet.cell(row, 10).value for row in range(22, sheet.max_row + 1)), \
    'No native layer description/interval exists in column J'
print('PASS: one worksheet, native intervals, no image covering form data')
